### ISSUE TITLE
IMG BBCode within URL BBCode doesn't get parsed

### ISSUE THREAD

**Issue by Elsensee** [phpbb-de/phpbb-ext-external-images-as-link#22]
As per [this post](https://www.phpbb.com/customise/db/extension/phpbb.de_external_images_as_link/support/topic/158696?p=584466#p584466) on phpBB.com

Apparently we mess too much with the new BBCode parser of 3.2.
As soon as this extension is installed, the IMG tag doesn't get parsed anymore when it's in a URL tag.

Lines that probably have to be changed and are the cause of this bug: https://github.com/phpbb-de/phpbb-ext-external-images-as-link/blob/33d8f2c656a123af58c0d62d5412a3d5d61ab15f/event/listener.php#L123-L126

Maybe, @JoshyPHP can help? :)

**Comment by JoshyPHP** [comment]
The issue is that this template is sometimes an image, sometimes a link. The HTML specs dictate that `a` elements cannot contain `a` elements so the library determines that this BBCode cannot be used inside of the `[url]` BBCode.

Depending on the version of the library that's bundled with phpBB, you may be able to force allowing it by executing this during `core.text_formatter_s9e_configure_after`:

```php
$configurator->tags['URL']->rules->allowChild('IMG');
$configurator->tags['URL']->rules->allowDescendant('IMG');
```

Alternatively, you may want to replace images with links in the HTML via `core.text_formatter_s9e_render_after`.

**Comment by Elsensee** [comment]
Wow! Thank you very very much!
I first thought, the way of allowing children/descendants wouldn't work and started coding the regular expressions for doing it on the HTML until I realized that phpBB wouldn't reparse the post if it didn't change.

It works, however, so thank you very much!

**Comment by Crizz0** [comment]
@JoshyPHP Is this not working with PHP 5.6 and lower?

**Comment by Crizz0** [comment]
Do you have the issue, too: https://github.com/phpbb-de/phpbb-ext-external-images-as-link/pull/23#issuecomment-332580011 ?
