### ISSUE TITLE
Only images *in* the board allowed

### ISSUE THREAD

**Issue by Elsensee** [phpbb-de/phpbb-ext-external-images-as-link#4]
Currently we are only allowing images which are in the directory or subdirectory of the board, since `generate_board_url();` returns the board url + script_path.
For phpBB.de it will return https://www.phpbb.de/community
Maybe we should check if we want this behaviour... ;)

**Comment by gn36** [comment]
We should probably allow more than just subfolders of the board. Also, there is no real security, because the limitation can be circumvented for other files on the server anyways, because the script only looks for images starting with the board url but doesn't check whether the remaining path contains ../, so one could simply use https://www.phpbb.de/community/../ to access https://www.phpbb.de/ and subfolders.
